---
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uptrace -d uptrace']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  uptrace:
    image: uptrace/uptrace:latest
    restart: on-failure
    volumes:
      - ./config/uptrace/uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - 14317:14317
      - 14318:14318
    depends_on:
      - clickhouse
      - postgres

volumes:
  clickhouse_data:
  postgres_data:
  uptrace_data:
