---
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    depends_on:
      jaeger:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./config/otel-collector/config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9464:9464"   # Prometheus metrics
      - "8888:8888"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    volumes:
      - ./config/jaeger/ui-config.json:/etc/jaeger/jaeger-ui.json
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      - "16686:16686"   # Jaeger UI
      # - "14317:4317"  # OTLP gRPC
      # - "14250:14250" # Jaeger gRPC
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"   # Prometheus UI
    restart: unless-stopped
    depends_on:
      otel-collector:
        condition: service_started

volumes:
  prometheus_data:
