---
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    volumes:
      - ./config/jaeger/ui-config.json:/etc/jaeger/jaeger-ui.json
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      - "16686:16686"   # Jaeger UI
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"   # Prometheus UI
    restart: unless-stopped
    depends_on:
      otel-collector:
        condition: service_started

volumes:
  prometheus_data:
