---
services:
  example:
    image: yolkhovyy/example:${EXAMPLE_VERSION:?must be set in .env}
    stop_signal: SIGINT
    depends_on:
      otel-collector:
        condition: service_started
    ports:
      - 8080:${EXAMPLE_HTTP_PORT:-8080}
    build:
      context: .
      dockerfile: cmd/example/Dockerfile
      target: ${BUILD_TARGET:-release}
    environment:
      - EXAMPLE_HTTP_PORT
      - EXAMPLE_HTTP_SHUTDOWNTIMEOUT
      - EXAMPLE_HTTP_READHEADERTIMEOUT
      - EXAMPLE_LOGGER_ENABLE
      - EXAMPLE_LOGGER_COLLECTOR_PROTOCOL
      - EXAMPLE_LOGGER_COLLECTOR_CONNECTION
      - EXAMPLE_TRACER_ENABLE
      - EXAMPLE_TRACER_COLLECTOR_PROTOCOL
      - EXAMPLE_TRACER_COLLECTOR_CONNECTION
      - EXAMPLE_METRIC_ENABLE
      - EXAMPLE_METRIC_PROMETHEUS
      - EXAMPLE_METRIC_INTERVAL
      - EXAMPLE_METRIC_COLLECTOR_PROTOCOL
      - EXAMPLE_METRIC_COLLECTOR_CONNECTION

include:
  - ./docker-compose.tm.yml
