@startuml datadog
title Telemetry Flow to Datadog
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

cloud Datadog {
    agent Logs
    agent Traces
    agent Metrics
}

EX --> OC
OC --> Logs: "Logs"
OC --> Traces: "Traces"
OC --> Metrics: "Metrics"

@enduml
