@startuml datadog
title Telemetry Flow to Datadog
left to right direction

agent Example as EX
agent "OTEL\nCollector" as OC
agent "go-otelw" as OW
cloud Datadog {
    agent Logs
    agent Traces
    agent Metrics
}

EX --> OW
OW --> OC
OC --> Logs: "Logs"
OC --> Traces: "Traces"
OC --> Metrics: "Metrics"

@enduml
