@startuml dynatrace
title Telemetry Flow to Dynatrace
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

cloud Dynatrace

EX --> OC
OC --> Dynatrace

@enduml
