@startuml elastic-kibana
title Telemetry Flow to Elasticsearch and Kibana
left to right direction

agent "Example\ngo-otelw" as EX
agent "OTEL\nCollector\n----\nconfig.yml" as OC

agent Elasticsearch as ES
agent Kibana

EX --> OC
OC --> ES
ES --> Kibana

@enduml
