@startuml elastic-kibana
title Telemetry Flow to Elasticsearch and Kibana
left to right direction

agent Example as EX
agent "OTEL\nCollector" as OC
agent "go-otelw" as OW
agent Elasticsearch as ES
agent Kibana

EX --> OW
OW --> OC
OC --> ES
ES --> Kibana

@enduml
