@startuml grafana-loki-jaeger
title Telemetry Flow to Grafana Loki Jaeger Prometheus
left to right direction

agent Example as EX
agent "go-otelw" as OW
agent "OTEL\nCollector" as OC
agent Loki
agent Jaeger
agent Prometheus
agent Grafana

EX --> OW
OW --> OC
OC --> Loki: "Logs"
OC --> Jaeger: "Traces"
OC --> Prometheus: "Metrics"
Loki --> Grafana
Jaeger --> Grafana
Prometheus --> Grafana

@enduml
