@startuml grafana-loki-tempo
title Telemetry Flow to Grafana Loki Tempo Prometheus
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC


agent Loki
agent Tempo
agent Prometheus
agent Grafana

EX --> OC
OC --> Loki: "Logs"
OC --> Tempo: "Traces"
OC --> Prometheus: "Metrics"
Loki --> Grafana
Tempo --> Grafana
Prometheus --> Grafana

@enduml
