@startuml grafana-cloud-alloy
title Telemetry Flow to Grafana Cloud via Alloy
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

agent Alloy as ALY
cloud "Grafana Cloud" {
    agent Loki
    agent Tempo
    agent Prometheus
    agent Grafana
}

EX --> OC
OC --> ALY
ALY --> Loki: "Logs"
ALY --> Tempo: "Traces"
ALY --> Prometheus: "Metrics"
Loki --> Grafana
Tempo --> Grafana
Prometheus --> Grafana

@enduml
