@startuml grafana-cloud
title Telemetry Flow to Grafana Cloud
left to right direction

agent "Example\ngo-otelw" as EX
agent "OTEL\nCollector\n----\nconfig.yml" as OC

cloud "Grafana Cloud" {
    agent Loki
    agent Tempo
    agent Prometheus
    agent Grafana
}

EX --> OW
OW --> OC
OC --> Loki: "Logs"
OC --> Tempo: "Traces"
OC --> Prometheus: "Metrics"
Loki --> Grafana
Tempo --> Grafana
Prometheus --> Grafana

@enduml
