@startuml grafana-loki-jaeger
title Telemetry Flow to Grafana Loki Jaeger Prometheus
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

agent Loki
agent Jaeger
agent Prometheus
agent Grafana

EX --> OC
OC --> Loki: "Logs"
OC --> Jaeger: "Traces"
OC --> Prometheus: "Metrics"
Loki --> Grafana
Jaeger --> Grafana
Prometheus --> Grafana

@enduml
