@startuml honeycomb
title Telemetry Flow to Honeycomb
left to right direction

agent "Example\ngo-otelw" as EX
agent "OTEL\nCollector\n----\nconfig.yml" as OC

cloud Honeycomb

EX --> OC
OC --> Honeycomb

@enduml
