@startuml honeycomb
title Telemetry Flow to Honeycomb
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC


cloud Honeycomb

EX --> OC
OC --> Honeycomb

@enduml
