@startuml new-relic
title Telemetry Flow to New Relic
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC


cloud "New Relic" {
    agent Logs
    agent Traces
    agent Metrics
}

EX --> OC
OC --> Logs: "Logs"
OC --> Traces: "Traces"
OC --> Metrics: "Metrics"

@enduml
