@startuml new-relic
title Telemetry Flow to New Relic
left to right direction

agent "Example\ngo-otelw" as EX
agent "OTEL\nCollector\n----\nconfig.yml" as OC

cloud "New Relic" {
    agent Logs
    agent Traces
    agent Metrics
}

EX --> OW
OW --> OC
OC --> Logs: "Logs"
OC --> Traces: "Traces"
OC --> Metrics: "Metrics"

@enduml
