@startuml new-relic
title Telemetry Flow to New Relic
left to right direction

agent Example as EX
agent "OTEL\nCollector" as OC
cloud "New Relic" {
    agent Logs
    agent Traces
    agent Metrics
}

EX --> OC
OC --> Logs: "Logs"
OC --> Traces: "Traces"
OC --> Metrics: "Metrics"

@enduml
