@startuml openobserve
title Telemetry Flow to OpenObserve
left to right direction

agent "Example\ngo-otelw" as EX
agent "OTEL\nCollector\n----\nconfig.yml" as OC

cloud OpenObserve

EX --> OC
OC --> OpenObserve

@enduml
