@startuml openobserve
title Telemetry Flow to OpenObserve
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

cloud OpenObserve

EX --> OC
OC --> OpenObserve

@enduml
