@startuml overview
title OpenTelemetry with go-otelw and OTEL Collector
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

cloud "Datadog" as DD
cloud "Dynatrace" as DT
cloud "Kibana\nElasticsearch" as EK
cloud "Grafana Loki\nJaeger/Tempo\nPrometheus" as G
cloud "Honeycomb" as HC
cloud "New Relic" as NR
cloud "OpenObserve" as OO
cloud "Uptrace" as UPT

EX -->> OC

OC --->> UPT
OC --->> OO
OC --->> NR
OC --->> EK
OC --->> HC
OC --->> G
OC --->> DT
OC --->> DD

note bottom of EX
Telemetry
Emitter:
* logs
* traces
* metrics
end note

note bottom of OC
Telemetry
Collector:
* receivers
* processors
* exporters
end note

note as TMB
Telemetry
Backends
aka
Observability
Backends
end note

UPT .[hidden]. TMB
OO .[hidden]. TMB
NR .[hidden]. TMB
HC .[hidden]. TMB
G .[hidden]. TMB
EK .[hidden]. TMB
DT .[hidden]. TMB
DD .[hidden]. TMB

@enduml
