@startuml overview
title Telemetry Flows
' left to right direction

cloud "Datadog" as DD
cloud "Dynatrace" as DT
cloud "Kibana\nElasticsearch" as EK
cloud "Grafana Loki\nJaeger/Tempo\nPrometheus" as G
cloud "Honeycomb" as HC
cloud "New Relic" as NR
cloud "Uptrace" as UPT

agent "go-otelw" as OW
agent "OTEL\nCollector" as OC
agent Example as EX

OC -up-> UPT
OC -up-> NR
OC -up-> EK
OC -up-> HC
OC -up-> G
OC -up-> DT
OC -up-> DD

EX -up-> OW
OW -UP-> OC

@enduml
