@startuml uptrace
title Telemetry Flow to Uptrace
left to right direction
skinparam handwritten true

agent "Example\ngo-otelw\n--\nconfig.yml" as EX
cloud "OTEL\nCollector\n--\nconfig.yml" as OC

agent Uptrace

EX --> OC
OC --> Uptrace

@enduml
