@startuml uptrace
title Telemetry Flow to Uptrace
left to right direction

agent Example as EX
agent "go-otelw" as OW
agent "OTEL\nCollector" as OC
agent Uptrace

EX --> OW
OW --> OC
OC --> Uptrace

@enduml
