---
logger:
  caller: true
  format: json
  level: trace
  timeFormat: 2006-01-02T15:04:05.999999999Z07:00
  otlp:
    protocol: grpc
    endpoint: foo:4242

tracer:
  enable: true
  otlp:
    protocol: grpc
    endpoint: foo:4242

metric:
  enable: true
  prometheus: true
  interval: 42s
  otlp:
    protocol: grpc
    endpoint: foo:4242
