---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    timeout: 5s
    collection_interval: 10s

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
    metrics:
      receivers: [otlp, docker_stats]
      processors: [batch]
      exporters: [prometheus, debug]

  telemetry:
    logs:
      level: debug

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
