---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlphttp/honeycomb:
    endpoint: "${env:HC_ENDPOINT}"
    headers:
      x-honeycomb-team: "${env:HC_TEAM}"

processors:
  batch:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/honeycomb, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/honeycomb, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/honeycomb, debug]
  telemetry:
    logs:
      level: debug

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
