---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp/openobserve:
    endpoint: api.openobserve.ai:5081
    headers:
      Authorization: "Basic ${env:OO_API_KEY}"
      organization: "${env:OO_ORG_ID}"
      stream-name: default
    tls:
      insecure: true
#   # Via HTTP
#   otlphttp/openobserve:
#     endpoint: "https://api.openobserve.ai/api/${env:OO_ORG_ID}"
#     headers:
#     Authorization: "Basic ${env:OO_API_KEY}"

processors:
  batch:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, debug]
  telemetry:
    logs:
      level: debug

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
